# Generated by Django 4.2.7 on 2025-10-06 20:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0001_initial"),
        ("contenttypes", "0002_remove_content_type_name"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("activities", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="TimelineEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("created", "Created"),
                            ("updated", "Updated"),
                            ("deleted", "Deleted"),
                            ("status_changed", "Status Changed"),
                            ("assigned", "Assigned"),
                            ("comment_added", "Comment Added"),
                            ("email_sent", "Email Sent"),
                            ("call_logged", "Call Logged"),
                            ("meeting_scheduled", "Meeting Scheduled"),
                            ("note_added", "Note Added"),
                            ("file_attached", "File Attached"),
                            ("converted", "Converted"),
                            ("other", "Other"),
                        ],
                        help_text="Type of timeline event",
                        max_length=50,
                    ),
                ),
                ("title", models.CharField(help_text="Event title", max_length=255)),
                (
                    "description",
                    models.TextField(blank=True, help_text="Event description"),
                ),
                (
                    "data",
                    models.JSONField(
                        blank=True, default=dict, help_text="Additional event data"
                    ),
                ),
                (
                    "object_id",
                    models.UUIDField(
                        blank=True, help_text="ID of the related entity", null=True
                    ),
                ),
                (
                    "is_system_event",
                    models.BooleanField(
                        default=False, help_text="Is this a system-generated event?"
                    ),
                ),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_set",
                        to="core.company",
                    ),
                ),
                (
                    "content_type",
                    models.ForeignKey(
                        blank=True,
                        help_text="Type of related entity",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="contenttypes.contenttype",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who triggered this event",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="timeline_events",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["company", "event_type"],
                        name="activities__company_a9383e_idx",
                    ),
                    models.Index(
                        fields=["company", "user"],
                        name="activities__company_264785_idx",
                    ),
                    models.Index(
                        fields=["company", "-created_at"],
                        name="activities__company_7c0b7b_idx",
                    ),
                    models.Index(
                        fields=["content_type", "object_id"],
                        name="activities__content_96a1fd_idx",
                    ),
                ],
            },
        ),
    ]
