# Generated by Django 4.2.7 on 2025-10-06 20:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("core", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="KPI",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                (
                    "kpi_type",
                    models.CharField(
                        choices=[
                            ("revenue", "Revenue"),
                            ("leads", "Leads"),
                            ("conversion", "Conversion Rate"),
                            ("deals", "Deals"),
                            ("custom", "Custom"),
                        ],
                        default="custom",
                        max_length=20,
                    ),
                ),
                ("formula", models.TextField(help_text="KPI calculation formula")),
                (
                    "target_value",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=15, null=True
                    ),
                ),
                ("unit", models.CharField(default="", max_length=50)),
                (
                    "period_type",
                    models.CharField(
                        choices=[
                            ("daily", "Daily"),
                            ("weekly", "Weekly"),
                            ("monthly", "Monthly"),
                            ("quarterly", "Quarterly"),
                            ("yearly", "Yearly"),
                        ],
                        default="monthly",
                        max_length=20,
                    ),
                ),
                ("is_public", models.BooleanField(default=False)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_set",
                        to="core.company",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="owned_kpis",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "kpi",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="SalesForecast",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                (
                    "forecast_type",
                    models.CharField(
                        choices=[
                            ("pipeline", "Pipeline Forecast"),
                            ("revenue", "Revenue Forecast"),
                            ("deals", "Deals Forecast"),
                        ],
                        default="pipeline",
                        max_length=20,
                    ),
                ),
                ("period_start", models.DateField()),
                ("period_end", models.DateField()),
                (
                    "forecasted_amount",
                    models.DecimalField(decimal_places=2, max_digits=15),
                ),
                (
                    "confidence_level",
                    models.DecimalField(
                        decimal_places=2,
                        default=50.0,
                        help_text="Confidence level percentage (0-100)",
                        max_digits=5,
                    ),
                ),
                (
                    "methodology",
                    models.CharField(
                        help_text="Forecast methodology used", max_length=100
                    ),
                ),
                ("assumptions", models.TextField(blank=True)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_set",
                        to="core.company",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="owned_forecasts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "sales_forecast",
                "ordering": ["-period_end"],
            },
        ),
        migrations.CreateModel(
            name="Report",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                (
                    "report_type",
                    models.CharField(
                        choices=[
                            ("table", "Table"),
                            ("chart", "Chart"),
                            ("pivot", "Pivot Table"),
                            ("summary", "Summary"),
                        ],
                        default="table",
                        max_length=20,
                    ),
                ),
                (
                    "chart_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("bar", "Bar Chart"),
                            ("line", "Line Chart"),
                            ("pie", "Pie Chart"),
                            ("area", "Area Chart"),
                            ("scatter", "Scatter Plot"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "data_source",
                    models.CharField(
                        help_text="Data source (e.g., 'accounts', 'deals', 'sales')",
                        max_length=100,
                    ),
                ),
                ("filters", models.JSONField(default=dict, help_text="Report filters")),
                ("columns", models.JSONField(default=list, help_text="Report columns")),
                (
                    "grouping",
                    models.JSONField(default=list, help_text="Grouping configuration"),
                ),
                (
                    "sorting",
                    models.JSONField(default=list, help_text="Sorting configuration"),
                ),
                ("is_public", models.BooleanField(default=False)),
                ("is_scheduled", models.BooleanField(default=False)),
                (
                    "schedule_frequency",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("daily", "Daily"),
                            ("weekly", "Weekly"),
                            ("monthly", "Monthly"),
                            ("quarterly", "Quarterly"),
                        ],
                        max_length=20,
                    ),
                ),
                ("schedule_time", models.TimeField(blank=True, null=True)),
                ("last_run", models.DateTimeField(blank=True, null=True)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_set",
                        to="core.company",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="owned_reports",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "shared_with",
                    models.ManyToManyField(
                        blank=True,
                        related_name="shared_reports",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "report",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Dashboard",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                ("is_default", models.BooleanField(default=False)),
                ("is_public", models.BooleanField(default=False)),
                (
                    "layout",
                    models.JSONField(
                        default=dict, help_text="Dashboard layout configuration"
                    ),
                ),
                (
                    "widgets",
                    models.JSONField(default=list, help_text="Dashboard widgets"),
                ),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_set",
                        to="core.company",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="owned_dashboards",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "shared_with",
                    models.ManyToManyField(
                        blank=True,
                        related_name="shared_dashboards",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "dashboard",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="SalesAnalytics",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("period_start", models.DateField()),
                ("period_end", models.DateField()),
                (
                    "total_revenue",
                    models.DecimalField(decimal_places=2, default=0, max_digits=15),
                ),
                (
                    "recurring_revenue",
                    models.DecimalField(decimal_places=2, default=0, max_digits=15),
                ),
                (
                    "new_revenue",
                    models.DecimalField(decimal_places=2, default=0, max_digits=15),
                ),
                ("total_deals", models.IntegerField(default=0)),
                ("won_deals", models.IntegerField(default=0)),
                ("lost_deals", models.IntegerField(default=0)),
                ("open_deals", models.IntegerField(default=0)),
                (
                    "win_rate",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Win rate percentage",
                        max_digits=5,
                    ),
                ),
                (
                    "average_deal_size",
                    models.DecimalField(decimal_places=2, default=0, max_digits=15),
                ),
                (
                    "average_sales_cycle",
                    models.IntegerField(
                        default=0, help_text="Average sales cycle in days"
                    ),
                ),
                (
                    "pipeline_value",
                    models.DecimalField(decimal_places=2, default=0, max_digits=15),
                ),
                (
                    "weighted_pipeline_value",
                    models.DecimalField(decimal_places=2, default=0, max_digits=15),
                ),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_set",
                        to="core.company",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sales_analytics",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "sales_analytics",
                "ordering": ["-period_end"],
                "unique_together": {("user", "period_start", "period_end")},
            },
        ),
        migrations.CreateModel(
            name="LeadAnalytics",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("period_start", models.DateField()),
                ("period_end", models.DateField()),
                ("total_leads", models.IntegerField(default=0)),
                ("new_leads", models.IntegerField(default=0)),
                ("qualified_leads", models.IntegerField(default=0)),
                ("converted_leads", models.IntegerField(default=0)),
                (
                    "lead_to_opportunity_rate",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Lead to opportunity conversion rate",
                        max_digits=5,
                    ),
                ),
                (
                    "lead_to_customer_rate",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Lead to customer conversion rate",
                        max_digits=5,
                    ),
                ),
                ("website_leads", models.IntegerField(default=0)),
                ("referral_leads", models.IntegerField(default=0)),
                ("cold_call_leads", models.IntegerField(default=0)),
                ("trade_show_leads", models.IntegerField(default=0)),
                ("email_campaign_leads", models.IntegerField(default=0)),
                ("social_media_leads", models.IntegerField(default=0)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_set",
                        to="core.company",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lead_analytics",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "lead_analytics",
                "ordering": ["-period_end"],
                "unique_together": {("user", "period_start", "period_end")},
            },
        ),
        migrations.CreateModel(
            name="KPIMeasurement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("period_start", models.DateField()),
                ("period_end", models.DateField()),
                ("value", models.DecimalField(decimal_places=2, max_digits=15)),
                (
                    "target_value",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=15, null=True
                    ),
                ),
                (
                    "variance",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Variance from target",
                        max_digits=15,
                        null=True,
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_set",
                        to="core.company",
                    ),
                ),
                (
                    "kpi",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="measurements",
                        to="analytics.kpi",
                    ),
                ),
            ],
            options={
                "db_table": "kpi_measurement",
                "ordering": ["-period_end"],
                "unique_together": {("kpi", "period_start", "period_end")},
            },
        ),
        migrations.CreateModel(
            name="ActivityAnalytics",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("period_start", models.DateField()),
                ("period_end", models.DateField()),
                ("total_activities", models.IntegerField(default=0)),
                ("completed_activities", models.IntegerField(default=0)),
                ("overdue_activities", models.IntegerField(default=0)),
                ("calls_count", models.IntegerField(default=0)),
                ("emails_count", models.IntegerField(default=0)),
                ("meetings_count", models.IntegerField(default=0)),
                ("demos_count", models.IntegerField(default=0)),
                (
                    "completion_rate",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Activity completion rate percentage",
                        max_digits=5,
                    ),
                ),
                (
                    "average_duration",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Average activity duration in minutes",
                        max_digits=8,
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_set",
                        to="core.company",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="activity_analytics",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "activity_analytics",
                "ordering": ["-period_end"],
                "unique_together": {("user", "period_start", "period_end")},
            },
        ),
    ]
