# Generated by Django 4.2.7 on 2025-10-06 20:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("crm", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Deal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(db_index=True, max_length=255)),
                ("description", models.TextField(blank=True)),
                (
                    "amount",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=15, null=True
                    ),
                ),
                (
                    "probability",
                    models.IntegerField(default=0, help_text="Probability percentage"),
                ),
                (
                    "stage",
                    models.CharField(
                        choices=[
                            ("prospecting", "Prospecting"),
                            ("qualification", "Qualification"),
                            ("proposal", "Proposal"),
                            ("negotiation", "Negotiation"),
                            ("closed_won", "Closed Won"),
                            ("closed_lost", "Closed Lost"),
                        ],
                        db_index=True,
                        default="prospecting",
                        max_length=50,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("open", "Open"),
                            ("won", "Won"),
                            ("lost", "Lost"),
                            ("cancelled", "Cancelled"),
                        ],
                        db_index=True,
                        default="open",
                        max_length=50,
                    ),
                ),
                ("expected_close_date", models.DateField(blank=True, null=True)),
                ("actual_close_date", models.DateField(blank=True, null=True)),
                ("custom_fields", models.JSONField(blank=True, null=True)),
                (
                    "account",
                    models.ForeignKey(
                        help_text="Associated account",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="deals",
                        to="crm.account",
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_set",
                        to="core.company",
                    ),
                ),
                (
                    "contact",
                    models.ForeignKey(
                        blank=True,
                        help_text="Primary contact",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="deals",
                        to="crm.contact",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        blank=True,
                        help_text="Sales rep who owns this deal",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="owned_deals",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Deal",
                "verbose_name_plural": "Deals",
                "db_table": "deals",
                "ordering": ["-created_at"],
            },
        ),
    ]
