# Prometheus Configuration for CRM Performance Monitoring

global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    cluster: 'crm-production'
    environment: 'production'

# Alerting configuration
alerting:
  alertmanagers:
    - static_configs:
        - targets:
            - 'alertmanager:9093'

# Rule files
rule_files:
  - 'alerts/performance_alerts.yml'
  - 'alerts/availability_alerts.yml'

# Scrape configurations
scrape_configs:
  # Django application metrics
  - job_name: 'crm-django'
    static_configs:
      - targets: ['web:8000']
    metrics_path: '/metrics/'
    scrape_interval: 30s
    scrape_timeout: 10s

  # Celery worker metrics
  - job_name: 'crm-celery'
    static_configs:
      - targets: ['celery-exporter:9540']
    scrape_interval: 30s

  # Redis metrics
  - job_name: 'redis'
    static_configs:
      - targets: ['redis-exporter:9121']
    scrape_interval: 30s

  # PostgreSQL metrics
  - job_name: 'postgresql'
    static_configs:
      - targets: ['postgres-exporter:9187']
    scrape_interval: 30s

  # Nginx metrics
  - job_name: 'nginx'
    static_configs:
      - targets: ['nginx:9113']
    scrape_interval: 30s

  # Node exporter (system metrics)
  - job_name: 'node'
    static_configs:
      - targets: ['node-exporter:9100']
    scrape_interval: 30s

  # OpenSearch metrics (if available)
  - job_name: 'opensearch'
    static_configs:
      - targets: ['opensearch:9200']
    metrics_path: '/_prometheus/metrics'
    scrape_interval: 30s

# Remote write configuration (optional, for long-term storage)
remote_write:
  - url: 'http://prometheus-remote-storage:9009/api/v1/write'
    queue_config:
      capacity: 10000
      max_shards: 5
      min_shards: 1
      max_samples_per_send: 1000
      batch_send_deadline: 5s
