# Generated by Django 4.2.7 on 2025-10-06 20:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("core", "0001_initial"),
        ("crm", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Campaign",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                (
                    "campaign_type",
                    models.CharField(
                        choices=[
                            ("email", "Email Campaign"),
                            ("social_media", "Social Media"),
                            ("content", "Content Marketing"),
                            ("paid_ads", "Paid Advertising"),
                            ("events", "Events"),
                            ("webinar", "Webinar"),
                            ("other", "Other"),
                        ],
                        default="email",
                        max_length=20,
                    ),
                ),
                (
                    "objective",
                    models.TextField(blank=True, help_text="Campaign objective"),
                ),
                (
                    "target_audience",
                    models.TextField(
                        blank=True, help_text="Target audience description"
                    ),
                ),
                (
                    "budget",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=15, null=True
                    ),
                ),
                ("currency", models.CharField(default="USD", max_length=3)),
                ("start_date", models.DateTimeField()),
                ("end_date", models.DateTimeField(blank=True, null=True)),
                ("created_date", models.DateTimeField(auto_now_add=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("scheduled", "Scheduled"),
                            ("active", "Active"),
                            ("paused", "Paused"),
                            ("completed", "Completed"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="draft",
                        max_length=20,
                    ),
                ),
                ("total_sent", models.IntegerField(default=0)),
                ("total_delivered", models.IntegerField(default=0)),
                ("total_opened", models.IntegerField(default=0)),
                ("total_clicked", models.IntegerField(default=0)),
                ("total_converted", models.IntegerField(default=0)),
                (
                    "delivery_rate",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Delivery rate percentage",
                        max_digits=5,
                    ),
                ),
                (
                    "open_rate",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Open rate percentage",
                        max_digits=5,
                    ),
                ),
                (
                    "click_rate",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Click rate percentage",
                        max_digits=5,
                    ),
                ),
                (
                    "conversion_rate",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Conversion rate percentage",
                        max_digits=5,
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_set",
                        to="core.company",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="owned_campaigns",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "campaign",
                "ordering": ["-created_date"],
            },
        ),
        migrations.CreateModel(
            name="MarketingAutomation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                (
                    "workflow_type",
                    models.CharField(
                        choices=[
                            ("welcome", "Welcome Series"),
                            ("nurture", "Nurture Sequence"),
                            ("abandoned_cart", "Abandoned Cart"),
                            ("re_engagement", "Re-engagement"),
                            ("birthday", "Birthday"),
                            ("anniversary", "Anniversary"),
                            ("custom", "Custom"),
                        ],
                        default="custom",
                        max_length=20,
                    ),
                ),
                (
                    "trigger_conditions",
                    models.JSONField(
                        default=dict, help_text="Workflow trigger conditions"
                    ),
                ),
                ("steps", models.JSONField(default=list, help_text="Workflow steps")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("active", "Active"),
                            ("paused", "Paused"),
                            ("completed", "Completed"),
                        ],
                        default="draft",
                        max_length=20,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("total_triggered", models.IntegerField(default=0)),
                ("total_completed", models.IntegerField(default=0)),
                ("total_dropped", models.IntegerField(default=0)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_set",
                        to="core.company",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="owned_automations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "marketing_automation",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="MarketingList",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                (
                    "list_type",
                    models.CharField(
                        choices=[
                            ("static", "Static List"),
                            ("dynamic", "Dynamic List"),
                            ("segment", "Segment"),
                        ],
                        default="static",
                        max_length=20,
                    ),
                ),
                (
                    "criteria",
                    models.JSONField(
                        default=dict, help_text="List criteria for dynamic lists"
                    ),
                ),
                ("filters", models.JSONField(default=dict, help_text="List filters")),
                ("total_contacts", models.IntegerField(default=0)),
                ("active_contacts", models.IntegerField(default=0)),
                ("unsubscribed_contacts", models.IntegerField(default=0)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_set",
                        to="core.company",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="owned_marketing_lists",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "marketing_list",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="MarketingAutomationExecution",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("triggered_date", models.DateTimeField(auto_now_add=True)),
                ("completed_date", models.DateTimeField(blank=True, null=True)),
                ("current_step", models.IntegerField(default=0)),
                ("total_steps", models.IntegerField(default=0)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("running", "Running"),
                            ("completed", "Completed"),
                            ("paused", "Paused"),
                            ("stopped", "Stopped"),
                        ],
                        default="running",
                        max_length=20,
                    ),
                ),
                (
                    "automation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="executions",
                        to="marketing.marketingautomation",
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_set",
                        to="core.company",
                    ),
                ),
                (
                    "contact",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="automation_executions",
                        to="crm.contact",
                    ),
                ),
                (
                    "lead",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="automation_executions",
                        to="crm.lead",
                    ),
                ),
            ],
            options={
                "db_table": "marketing_automation_execution",
                "ordering": ["-triggered_date"],
            },
        ),
        migrations.CreateModel(
            name="LeadScore",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "score",
                    models.IntegerField(default=0, help_text="Lead score (0-100)"),
                ),
                ("score_date", models.DateTimeField(auto_now_add=True)),
                (
                    "score_reason",
                    models.TextField(blank=True, help_text="Reason for score change"),
                ),
                ("email_score", models.IntegerField(default=0)),
                ("phone_score", models.IntegerField(default=0)),
                ("company_score", models.IntegerField(default=0)),
                ("industry_score", models.IntegerField(default=0)),
                ("revenue_score", models.IntegerField(default=0)),
                ("budget_score", models.IntegerField(default=0)),
                ("activity_score", models.IntegerField(default=0)),
                ("engagement_score", models.IntegerField(default=0)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_set",
                        to="core.company",
                    ),
                ),
                (
                    "lead",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="scores",
                        to="crm.lead",
                    ),
                ),
            ],
            options={
                "db_table": "lead_score",
                "ordering": ["-score_date"],
            },
        ),
        migrations.CreateModel(
            name="EmailTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=255)),
                ("subject", models.CharField(max_length=255)),
                (
                    "template_type",
                    models.CharField(
                        choices=[
                            ("welcome", "Welcome Email"),
                            ("newsletter", "Newsletter"),
                            ("promotional", "Promotional"),
                            ("follow_up", "Follow Up"),
                            ("nurture", "Nurture Sequence"),
                            ("custom", "Custom"),
                        ],
                        default="custom",
                        max_length=20,
                    ),
                ),
                ("html_content", models.TextField(blank=True)),
                ("text_content", models.TextField(blank=True)),
                (
                    "preview_text",
                    models.CharField(
                        blank=True, help_text="Email preview text", max_length=255
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("is_public", models.BooleanField(default=False)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_set",
                        to="core.company",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="owned_email_templates",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "email_template",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="EmailCampaign",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=255)),
                ("subject", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                ("html_content", models.TextField(blank=True)),
                ("text_content", models.TextField(blank=True)),
                ("preview_text", models.CharField(blank=True, max_length=255)),
                ("send_date", models.DateTimeField(blank=True, null=True)),
                ("timezone", models.CharField(default="UTC", max_length=50)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("scheduled", "Scheduled"),
                            ("sending", "Sending"),
                            ("sent", "Sent"),
                            ("paused", "Paused"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="draft",
                        max_length=20,
                    ),
                ),
                ("total_sent", models.IntegerField(default=0)),
                ("total_delivered", models.IntegerField(default=0)),
                ("total_opened", models.IntegerField(default=0)),
                ("total_clicked", models.IntegerField(default=0)),
                ("total_bounced", models.IntegerField(default=0)),
                ("total_unsubscribed", models.IntegerField(default=0)),
                (
                    "campaign",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="email_campaigns",
                        to="marketing.campaign",
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_set",
                        to="core.company",
                    ),
                ),
                (
                    "marketing_list",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="email_campaigns",
                        to="marketing.marketinglist",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="owned_email_campaigns",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "template",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="email_campaigns",
                        to="marketing.emailtemplate",
                    ),
                ),
            ],
            options={
                "db_table": "email_campaign",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="EmailActivity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "activity_type",
                    models.CharField(
                        choices=[
                            ("sent", "Sent"),
                            ("delivered", "Delivered"),
                            ("opened", "Opened"),
                            ("clicked", "Clicked"),
                            ("bounced", "Bounced"),
                            ("unsubscribed", "Unsubscribed"),
                            ("complained", "Complained"),
                        ],
                        max_length=20,
                    ),
                ),
                ("activity_date", models.DateTimeField(auto_now_add=True)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("user_agent", models.TextField(blank=True)),
                ("link_url", models.URLField(blank=True, help_text="Clicked link URL")),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_set",
                        to="core.company",
                    ),
                ),
                (
                    "contact",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="email_activities",
                        to="crm.contact",
                    ),
                ),
                (
                    "email_campaign",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="activities",
                        to="marketing.emailcampaign",
                    ),
                ),
            ],
            options={
                "db_table": "email_activity",
                "ordering": ["-activity_date"],
            },
        ),
        migrations.CreateModel(
            name="MarketingListContact",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("added_date", models.DateTimeField(auto_now_add=True)),
                ("is_active", models.BooleanField(default=True)),
                ("is_unsubscribed", models.BooleanField(default=False)),
                ("unsubscribed_date", models.DateTimeField(blank=True, null=True)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_set",
                        to="core.company",
                    ),
                ),
                (
                    "contact",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="marketing_lists",
                        to="crm.contact",
                    ),
                ),
                (
                    "marketing_list",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="list_contacts",
                        to="marketing.marketinglist",
                    ),
                ),
            ],
            options={
                "db_table": "marketing_list_contact",
                "unique_together": {("marketing_list", "contact")},
            },
        ),
        migrations.AddIndex(
            model_name="campaign",
            index=models.Index(
                fields=["company", "name"], name="campaign_company_2e530b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="campaign",
            index=models.Index(
                fields=["company", "campaign_type"], name="campaign_company_f38013_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="campaign",
            index=models.Index(
                fields=["company", "status"], name="campaign_company_991c96_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="campaign",
            index=models.Index(
                fields=["company", "owner"], name="campaign_company_a21d0a_idx"
            ),
        ),
    ]
