# Generated by Django 4.2.7 on 2025-10-06 20:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("core", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Territory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=255)),
                ("code", models.CharField(max_length=50, unique=True)),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("geographic", "Geographic"),
                            ("industry", "Industry"),
                            ("account_size", "Account Size"),
                            ("product_line", "Product Line"),
                        ],
                        default="geographic",
                        max_length=50,
                    ),
                ),
                ("description", models.TextField(blank=True)),
                (
                    "countries",
                    models.JSONField(
                        blank=True, help_text="List of country codes", null=True
                    ),
                ),
                (
                    "states",
                    models.JSONField(
                        blank=True, help_text="List of state/province codes", null=True
                    ),
                ),
                (
                    "cities",
                    models.JSONField(blank=True, help_text="List of cities", null=True),
                ),
                (
                    "industries",
                    models.JSONField(
                        blank=True, help_text="List of industries", null=True
                    ),
                ),
                (
                    "account_sizes",
                    models.JSONField(
                        blank=True, help_text="Account size ranges", null=True
                    ),
                ),
                (
                    "product_lines",
                    models.JSONField(
                        blank=True, help_text="Product line IDs", null=True
                    ),
                ),
                (
                    "assignment_rules",
                    models.JSONField(
                        blank=True, help_text="Auto-assignment rules", null=True
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_set",
                        to="core.company",
                    ),
                ),
                (
                    "manager",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="managed_territories",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "parent_territory",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sub_territories",
                        to="territories.territory",
                    ),
                ),
            ],
            options={
                "db_table": "territory",
                "ordering": ["name"],
                "indexes": [
                    models.Index(
                        fields=["company", "name"], name="territory_company_677c4b_idx"
                    ),
                    models.Index(
                        fields=["company", "type"], name="territory_company_a4557e_idx"
                    ),
                    models.Index(
                        fields=["company", "manager"],
                        name="territory_company_845d5e_idx",
                    ),
                    models.Index(
                        fields=["company", "is_active"],
                        name="territory_company_970bd8_idx",
                    ),
                ],
            },
        ),
    ]
