# Generated by Django 4.2.7 on 2025-10-06 20:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("core", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ApprovalProcess",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                (
                    "process_type",
                    models.CharField(
                        choices=[
                            ("sequential", "Sequential Approval"),
                            ("parallel", "Parallel Approval"),
                            ("conditional", "Conditional Approval"),
                            ("escalation", "Escalation Approval"),
                        ],
                        default="sequential",
                        max_length=20,
                    ),
                ),
                (
                    "entity_type",
                    models.CharField(
                        help_text="Entity type this process applies to", max_length=100
                    ),
                ),
                (
                    "approval_rules",
                    models.JSONField(
                        default=dict, help_text="Approval rules and conditions"
                    ),
                ),
                (
                    "approvers",
                    models.JSONField(default=list, help_text="List of approvers"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_set",
                        to="core.company",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="owned_approval_processes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "approval_process",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="BusinessRule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                (
                    "rule_type",
                    models.CharField(
                        choices=[
                            ("validation", "Validation Rule"),
                            ("calculation", "Calculation Rule"),
                            ("assignment", "Assignment Rule"),
                            ("notification", "Notification Rule"),
                            ("escalation", "Escalation Rule"),
                            ("custom", "Custom Rule"),
                        ],
                        default="custom",
                        max_length=20,
                    ),
                ),
                (
                    "entity_type",
                    models.CharField(
                        help_text="Entity type this rule applies to", max_length=100
                    ),
                ),
                (
                    "conditions",
                    models.JSONField(default=dict, help_text="Rule conditions"),
                ),
                ("actions", models.JSONField(default=list, help_text="Rule actions")),
                (
                    "priority",
                    models.IntegerField(
                        default=0,
                        help_text="Rule priority (higher number = higher priority)",
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "is_global",
                    models.BooleanField(
                        default=False, help_text="Apply to all companies"
                    ),
                ),
                ("execution_count", models.IntegerField(default=0)),
                ("last_executed", models.DateTimeField(blank=True, null=True)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_set",
                        to="core.company",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="owned_business_rules",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "business_rule",
                "ordering": ["-priority", "name"],
            },
        ),
        migrations.CreateModel(
            name="Workflow",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                (
                    "workflow_type",
                    models.CharField(
                        choices=[
                            ("approval", "Approval Workflow"),
                            ("notification", "Notification Workflow"),
                            ("automation", "Automation Workflow"),
                            ("escalation", "Escalation Workflow"),
                            ("custom", "Custom Workflow"),
                        ],
                        default="custom",
                        max_length=20,
                    ),
                ),
                (
                    "trigger_conditions",
                    models.JSONField(
                        default=dict, help_text="Workflow trigger conditions"
                    ),
                ),
                (
                    "steps",
                    models.JSONField(
                        default=list, help_text="Workflow steps configuration"
                    ),
                ),
                (
                    "rules",
                    models.JSONField(default=dict, help_text="Workflow business rules"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("active", "Active"),
                            ("inactive", "Inactive"),
                            ("archived", "Archived"),
                        ],
                        default="draft",
                        max_length=20,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "is_global",
                    models.BooleanField(
                        default=False, help_text="Available to all companies"
                    ),
                ),
                ("execution_count", models.IntegerField(default=0)),
                ("last_executed", models.DateTimeField(blank=True, null=True)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_set",
                        to="core.company",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="owned_workflows",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "workflow",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="WorkflowExecution",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "trigger_data",
                    models.JSONField(
                        default=dict, help_text="Data that triggered the workflow"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("running", "Running"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                            ("cancelled", "Cancelled"),
                            ("paused", "Paused"),
                        ],
                        default="running",
                        max_length=20,
                    ),
                ),
                ("current_step", models.IntegerField(default=0)),
                ("total_steps", models.IntegerField(default=0)),
                ("started_at", models.DateTimeField(auto_now_add=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("paused_at", models.DateTimeField(blank=True, null=True)),
                (
                    "result_data",
                    models.JSONField(
                        default=dict, help_text="Workflow execution results"
                    ),
                ),
                ("error_message", models.TextField(blank=True)),
                ("error_details", models.JSONField(default=dict)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_set",
                        to="core.company",
                    ),
                ),
                (
                    "triggered_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="triggered_workflows",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "workflow",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="executions",
                        to="workflow.workflow",
                    ),
                ),
            ],
            options={
                "db_table": "workflow_execution",
                "ordering": ["-started_at"],
            },
        ),
        migrations.CreateModel(
            name="ProcessTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                (
                    "template_type",
                    models.CharField(
                        choices=[
                            ("onboarding", "Onboarding"),
                            ("offboarding", "Offboarding"),
                            ("approval", "Approval"),
                            ("notification", "Notification"),
                            ("escalation", "Escalation"),
                            ("custom", "Custom"),
                        ],
                        default="custom",
                        max_length=20,
                    ),
                ),
                (
                    "process_steps",
                    models.JSONField(
                        default=list, help_text="Process steps configuration"
                    ),
                ),
                (
                    "variables",
                    models.JSONField(default=list, help_text="Template variables"),
                ),
                (
                    "settings",
                    models.JSONField(default=dict, help_text="Template settings"),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "is_public",
                    models.BooleanField(
                        default=False, help_text="Available to all companies"
                    ),
                ),
                ("usage_count", models.IntegerField(default=0)),
                ("last_used", models.DateTimeField(blank=True, null=True)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_set",
                        to="core.company",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="owned_process_templates",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "process_template",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="BusinessRuleExecution",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("entity_type", models.CharField(max_length=100)),
                ("entity_id", models.CharField(max_length=100)),
                (
                    "execution_data",
                    models.JSONField(
                        default=dict, help_text="Data used in rule execution"
                    ),
                ),
                ("success", models.BooleanField(default=True)),
                (
                    "result_data",
                    models.JSONField(default=dict, help_text="Rule execution results"),
                ),
                ("error_message", models.TextField(blank=True)),
                ("executed_at", models.DateTimeField(auto_now_add=True)),
                ("execution_time_ms", models.IntegerField(blank=True, null=True)),
                (
                    "business_rule",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="executions",
                        to="workflow.businessrule",
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_set",
                        to="core.company",
                    ),
                ),
            ],
            options={
                "db_table": "business_rule_execution",
                "ordering": ["-executed_at"],
            },
        ),
        migrations.CreateModel(
            name="ApprovalRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("entity_type", models.CharField(max_length=100)),
                ("entity_id", models.CharField(max_length=100)),
                (
                    "entity_data",
                    models.JSONField(
                        default=dict, help_text="Entity data being approved"
                    ),
                ),
                ("request_reason", models.TextField(blank=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("requested_at", models.DateTimeField(auto_now_add=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("approval_notes", models.TextField(blank=True)),
                ("rejection_reason", models.TextField(blank=True)),
                (
                    "approval_process",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="requests",
                        to="workflow.approvalprocess",
                    ),
                ),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="approved_requests",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_set",
                        to="core.company",
                    ),
                ),
                (
                    "requested_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="approval_requests",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "approval_request",
                "ordering": ["-requested_at"],
            },
        ),
    ]
